### ISSUE TITLE
Error while sending settings to websites at startup

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless-Link#167]
```
Exception in thread "pool-3-thread-20" java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "is" is null
  at com.namelessmc.java_api.RequestHandler.getBytesFromInputStream(RequestHandler.java:183)
  at com.namelessmc.java_api.RequestHandler.makeConnection(RequestHandler.java:135)
  at com.namelessmc.java_api.RequestHandler.post(RequestHandler.java:52)
  at com.namelessmc.java_api.NamelessAPI.setDiscordBotUrl(NamelessAPI.java:412)
  at com.namelessmc.bot.Main.lambda$main$0(Main.java:246)
  at com.namelessmc.bot.Main$$Lambda$266/0x00000000c62851b8.run(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless-Java-API/commit/8be2026dc179298d169100f50182d4d9268e8204
