### ISSUE TITLE
Storage Backend Error /configure

### ISSUE THREAD

**Issue by LightDevil96** [NamelessMC/Nameless-Link#434]
I run start.sh and all is connected but after use /configure, show this:

Dec 02, 2023 4:48:30 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
[main] INFO com.namelessmc.bot.Main - Sending bot settings to https://xxx.net/index.php?route=/api/v2/
[main] INFO com.namelessmc.bot.Main - Sent bot settings to website and registered commands successfully.
[pool-1-thread-2] INFO Group sync discord->website - Sending roles for guild xxx to website
[JDA [0 / 1] MainWS-ReadThread] INFO com.namelessmc.bot.listeners.CommandListener - User xxx ran command /configure in guild xxxx
[pool-1-thread-4] INFO com.namelessmc.bot.commands.ConfigureCommand - Subcommand: link
[pool-1-thread-4] INFO com.namelessmc.bot.commands.ConfigureCommand - Checking if API URL works...
[pool-1-thread-4] INFO com.namelessmc.bot.commands.ConfigureCommand - Making request to info endpoint
[pool-1-thread-4] INFO com.namelessmc.bot.commands.ConfigureCommand - Website connection is working
[pool-1-thread-4] INFO com.namelessmc.bot.commands.ConfigureCommand - API URL seems to work. Sending bot settings...
[pool-1-thread-4] ERROR com.namelessmc.bot.commands.ConfigureCommand - storage backend
com.namelessmc.bot.connections.BackendStorageException: java.lang.UnsupportedOperationException
        at com.namelessmc.bot.connections.StatelessConnectionManager.updateConnection(StatelessConnectionManager.java:54)
        at com.namelessmc.bot.commands.ConfigureCommand.link(ConfigureCommand.java:147)
        at com.namelessmc.bot.commands.ConfigureCommand.lambda$execute$0(ConfigureCommand.java:72)
        at com.namelessmc.bot.Main.lambda$canModifySettings$2(Main.java:280)
        at net.dv8tion.jda.internal.requests.DeferredRestAction.queue(DeferredRestAction.java:148)
        at com.namelessmc.bot.Main.canModifySettings(Main.java:278)
        at com.namelessmc.bot.commands.ConfigureCommand.execute(ConfigureCommand.java:62)
        at com.namelessmc.bot.listeners.CommandListener.lambda$onSlashCommandInteraction$0(CommandListener.java:55)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.UnsupportedOperationException
        ... 14 more
[pool-1-thread-4] INFO com.namelessmc.bot.commands.ConfigureCommand - link

**Comment by LightDevil96** [comment]
Sorry my wrong, i am idiot xD
After installation
Solved in: Skip the /configure command step, you have already configured the bot using environment variables.

**Comment by LightDevil96** [comment]
I love namelessmc project and using everytime, thanks for dev team, for work and time!

**Comment by Derkades** [comment]
I will reopen this issue, Nameless-Link should probably send a more user friendly message instead

**Comment by FluxxyBoi** [comment]
Fixed in #506
