### ISSUE TITLE
setUsernameSyncEnabled

### ISSUE THREAD

**Issue by DLmass** [NamelessMC/Nameless-Link#436]
"/configure username_sync state:true" threw this error

[pool-1-thread-1] INFO com.namelessmc.bot.commands.ConfigureCommand - Subcommand: username_sync
[pool-1-thread-1] ERROR com.namelessmc.bot.commands.ConfigureCommand - storage backend
com.namelessmc.bot.connections.BackendStorageException: java.lang.UnsupportedOperationException
	at com.namelessmc.bot.connections.StatelessConnectionManager.setUsernameSyncEnabled(StatelessConnectionManager.java:77)
	at com.namelessmc.bot.commands.ConfigureCommand.changeUsernameSync(ConfigureCommand.java:248)
	at com.namelessmc.bot.commands.ConfigureCommand.lambda$execute$0(ConfigureCommand.java:75)
	at com.namelessmc.bot.Main.lambda$canModifySettings$2(Main.java:280)
	at net.dv8tion.jda.internal.requests.DeferredRestAction.queue(DeferredRestAction.java:148)
	at com.namelessmc.bot.Main.canModifySettings(Main.java:278)
	at com.namelessmc.bot.commands.ConfigureCommand.execute(ConfigureCommand.java:62)
	at com.namelessmc.bot.listeners.CommandListener.lambda$onSlashCommandInteraction$0(CommandListener.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.UnsupportedOperationException
	... 14 more
[pool-1-thread-1] INFO com.namelessmc.bot.commands.ConfigureCommand - username_sync

**Comment by Derkades** [comment]
In stateless mode, the bot should be configured using environment variables instead of /configure: https://github.com/NamelessMC/Nameless-Link/wiki/Environment-variables
